-- Train Ticket Management System Database Schema
-- This file contains all the SQL DDL statements for creating the database tables

-- Drop tables if they exist (for clean startup)
DROP TABLE IF EXISTS passenger;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS fare_type;
DROP TABLE IF EXISTS train_schedule;
DROP TABLE IF EXISTS train;
DROP TABLE IF EXISTS users;

-- 1. Users table
CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL,
    role VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Train table
CREATE TABLE train (
    train_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_name VARCHAR(100) NOT NULL,
    source VARCHAR(100) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    departure_time TIME NOT NULL,
    arrival_time TIME NOT NULL,
    status VARCHAR(10) DEFAULT 'ACTIVE'
);

-- 3. TrainSchedule table
CREATE TABLE train_schedule (
    schedule_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_id INT NOT NULL,
    day_of_week VARCHAR(3),
    FOREIGN KEY (train_id) REFERENCES train(train_id) ON DELETE CASCADE
);

-- 4. FareType table
CREATE TABLE fare_type (
    fare_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_id INT NOT NULL,
    class_type VARCHAR(20),
    price DECIMAL(10,2) NOT NULL,
    seats_available INT NOT NULL,
    FOREIGN KEY (train_id) REFERENCES train(train_id) ON DELETE CASCADE
);

-- 5. Booking table
CREATE TABLE booking (
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    train_id INT NOT NULL,
    fare_type_id INT NOT NULL,
    journey_date DATE NOT NULL,
    booking_date DATE DEFAULT CURRENT_DATE,
    total_fare DECIMAL(10,2) NOT NULL,
    status VARCHAR(15) DEFAULT 'CONFIRMED',
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (train_id) REFERENCES train(train_id),
    FOREIGN KEY (fare_type_id) REFERENCES fare_type(fare_type_id)
);

-- 6. Passenger table
CREATE TABLE passenger (
    passenger_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    gender VARCHAR(10),
    id_proof VARCHAR(50) NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES booking(booking_id) ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_train_source_destination ON train(source, destination);
CREATE INDEX idx_train_schedule_train_day ON train_schedule(train_id, day_of_week);
CREATE INDEX idx_fare_type_train ON fare_type(train_id);
CREATE INDEX idx_booking_user ON booking(user_id);
CREATE INDEX idx_booking_train ON booking(train_id);
CREATE INDEX idx_booking_journey_date ON booking(journey_date);
CREATE INDEX idx_passenger_booking ON passenger(booking_id);

-- Insert sample data for testing (optional)
-- Sample admin user (password: Admin@123 - BCrypt encrypted)
INSERT INTO users (username, password, email, phone, role) 
VALUES ('admin', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin@trainsystem.com', '9876543210', 'ADMIN');

-- Sample regular user (password: John@123 - BCrypt encrypted)
INSERT INTO users (username, password, email, phone, role) 
VALUES ('john_doe', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'john.doe@email.com', '9876543211', 'USER');

-- Sample train
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) 
VALUES ('Rajdhani Express', 'Delhi', 'Mumbai', '08:00:00', '20:00:00', 'ACTIVE');

-- Sample train schedule
INSERT INTO train_schedule (train_id, day_of_week) 
VALUES (1, 'MON'), (1, 'WED'), (1, 'FRI');

-- Sample fare types
INSERT INTO fare_type (train_id, class_type, price, seats_available) 
VALUES (1, '1AC', 2500.00, 50), (1, '2AC', 1500.00, 100), (1, 'SL', 800.00, 200);

-- Additional sample trains for comprehensive testing
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Garib Rath 100', 'Pune', 'Bangalore', '18:15:00', '02:45:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Vande Bharat 101', 'Lucknow', 'Kolkata', '05:00:00', '11:45:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Tejas Express 102', 'Ahmedabad', 'Jaipur', '19:30:00', '00:45:00', 'INACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Double Decker 103', 'Lucknow', 'Ahmedabad', '20:45:00', '04:30:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Vande Bharat 104', 'Pune', 'Jaipur', '11:30:00', '21:00:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Rajdhani Express 105', 'Lucknow', 'Pune', '05:15:00', '14:45:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Jan Shatabdi 106', 'Delhi', 'Ahmedabad', '16:30:00', '02:45:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Jan Shatabdi 107', 'Mumbai', 'Lucknow', '04:00:00', '14:45:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Intercity Express 108', 'Delhi', 'Jaipur', '21:00:00', '04:15:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Garib Rath 109', 'Pune', 'Kolkata', '08:15:00', '13:45:00', 'INACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Shatabdi Express 110', 'Hyderabad', 'Ahmedabad', '16:30:00', '04:30:00', 'INACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Humsafar Express 111', 'Kolkata', 'Hyderabad', '03:45:00', '15:00:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Jan Shatabdi 112', 'Hyderabad', 'Kolkata', '14:00:00', '23:45:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Double Decker 113', 'Bangalore', 'Mumbai', '23:15:00', '10:30:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Intercity Express 114', 'Ahmedabad', 'Mumbai', '15:00:00', '22:15:00', 'INACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Garib Rath 115', 'Pune', 'Kolkata', '20:15:00', '02:45:00', 'INACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Duronto Express 116', 'Jaipur', 'Delhi', '10:00:00', '19:15:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Intercity Express 117', 'Kolkata', 'Chennai', '11:00:00', '20:15:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Humsafar Express 118', 'Delhi', 'Lucknow', '00:45:00', '07:45:00', 'ACTIVE');
INSERT INTO train (train_name, source, destination, departure_time, arrival_time, status) VALUES ('Duronto Express 119', 'Mumbai', 'Bangalore', '03:30:00', '10:45:00', 'ACTIVE');

-- Additional fare types for comprehensive testing
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (2, '2AC', 1286, 99);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (2, 'SL', 2168, 107);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (3, '2AC', 1054, 105);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (3, 'Sleeper-AC', 1751, 53);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (4, '2AC', 1932, 138);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (4, '1AC', 1609, 160);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (5, 'Sleeper-AC', 2149, 106);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (5, 'Seat', 1356, 194);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (6, '1AC', 2520, 185);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (6, '3AC', 2075, 81);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (7, 'SL', 459, 77);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (7, 'SL', 1658, 185);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (8, 'Seat', 796, 149);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (8, '1AC', 1287, 113);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (9, 'SL', 1588, 200);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (9, 'Seat', 2048, 126);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (10, '3AC', 1608, 193);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (10, 'SL', 1564, 131);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (11, '2AC', 2549, 174);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (11, '3AC', 2891, 122);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (12, 'Sleeper-AC', 924, 90);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (12, '2AC', 1916, 56);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (13, '1AC', 2642, 140);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (13, 'Sleeper-NonAC', 2333, 144);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (14, '1AC', 2586, 150);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (14, 'Seat', 2917, 103);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (15, '3AC', 2943, 82);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (15, 'SL', 1840, 72);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (16, 'Sleeper-NonAC', 992, 129);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (16, '3AC', 2645, 61);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (17, 'SL', 1610, 69);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (17, 'Sleeper-AC', 320, 129);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (18, '1AC', 333, 156);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (18, 'Sleeper-NonAC', 340, 98);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (19, 'Sleeper-NonAC', 557, 135);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (19, 'SL', 2231, 184);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (20, 'Seat', 2113, 61);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (20, '1AC', 1522, 161);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (21, 'Sleeper-AC', 550, 181);
INSERT INTO fare_type (train_id, class_type, price, seats_available) VALUES (21, 'Sleeper-NonAC', 2953, 126);

-- Additional train schedules for comprehensive testing
INSERT INTO train_schedule (train_id, day_of_week) VALUES (2, 'SAT');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (2, 'MON');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (2, 'FRI');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (3, 'WED');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (3, 'THU');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (3, 'SUN');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (4, 'SUN');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (4, 'MON');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (5, 'WED');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (5, 'TUE');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (5, 'MON');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (6, 'SUN');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (6, 'FRI');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (7, 'WED');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (7, 'TUE');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (7, 'MON');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (8, 'SAT');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (8, 'TUE');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (8, 'SUN');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (9, 'WED');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (9, 'SAT');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (9, 'MON');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (10, 'SAT');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (10, 'FRI');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (11, 'WED');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (11, 'THU');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (11, 'FRI');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (12, 'SAT');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (13, 'TUE');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (13, 'SUN');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (13, 'MON');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (14, 'THU');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (14, 'MON');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (14, 'FRI');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (15, 'SUN');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (16, 'SAT');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (16, 'TUE');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (16, 'THU');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (17, 'THU');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (17, 'SUN');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (17, 'MON');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (18, 'SAT');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (18, 'WED');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (18, 'FRI');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (19, 'SAT');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (19, 'TUE');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (19, 'THU');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (20, 'WED');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (20, 'TUE');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (20, 'FRI');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (21, 'TUE');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (21, 'SUN');
INSERT INTO train_schedule (train_id, day_of_week) VALUES (21, 'FRI');


